### ISSUE TITLE
Why is this module not using dsmcad?

### ISSUE THREAD

**Issue by janorn** [nosolutions/puppet-tsm#10]
Why is dsmc sch used instead of dsmcad for starting the tsm client?

http://www-01.ibm.com/support/docview.wss?uid=swg21358414

**Comment by tosmi** [comment]
simply because i didn't know about dsmcad. we were always running the dsmc scheduler. i'm happy to merge pull requests for enabling dsmcad support in this module. i'll also look into moving to dsmcad, but this may take some time, simply because we are currently using dmsc sched for about 1100 nodes, changing this setup to dsmcad will take some time and planning.
one question: is the webconsole thing dsmcad provides optional? i'm not happy starting a web server on every tsm client we have... 

thanks for the input
toni

**Comment by tosmi** [comment]
so it seems the webconsole is optional, but not the cadport. i think we will stick with dsmc sched,
if someone wants to implement dsmcad support feel free and please send a pull request. the next release of puppet-tsm will hopefully support restarting the dsmc sched on config file changes.

**Comment by tosmi** [comment]
this should be fixed with pull request #43. dsmcad is now supported
